# Generated by Django 5.1.1 on 2024-12-08 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorProductos', '0002_producto_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorProductos.categoria'),
        ),
    ]
